name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  atomic_design_system:
    git:
      url: https://github.com/Marisolperez22/atomic_desing_system.git
      path: atomic_design_system
  either_dart: ^1.0.0
  fake_store_get_request:
    git:
      url: https://github.com/Marisolperez22/fake_store_get_request
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  go_router: ^16.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
