// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:either_dart/either.dart' as _i13;
import 'package:fake_store_get_request/data/models/cart.dart' as _i10;
import 'package:fake_store_get_request/data/models/login_response.dart' as _i9;
import 'package:fake_store_get_request/data/models/product.dart' as _i8;
import 'package:fake_store_get_request/domain/usecases/get_categories.dart'
    as _i5;
import 'package:fake_store_get_request/domain/usecases/get_product_by_category.dart'
    as _i6;
import 'package:fake_store_get_request/domain/usecases/get_product_detail.dart'
    as _i3;
import 'package:fake_store_get_request/domain/usecases/get_products.dart'
    as _i2;
import 'package:fake_store_get_request/domain/usecases/get_user_cart.dart'
    as _i7;
import 'package:fake_store_get_request/domain/usecases/login.dart' as _i4;
import 'package:fake_store_get_request/services/fake_store_service.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetProducts_0 extends _i1.SmartFake implements _i2.GetProducts {
  _FakeGetProducts_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetProductDetail_1 extends _i1.SmartFake
    implements _i3.GetProductDetail {
  _FakeGetProductDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogin_2 extends _i1.SmartFake implements _i4.Login {
  _FakeLogin_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCategories_3 extends _i1.SmartFake implements _i5.GetCategories {
  _FakeGetCategories_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetProductByCategory_4 extends _i1.SmartFake
    implements _i6.GetProductByCategory {
  _FakeGetProductByCategory_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserCart_5 extends _i1.SmartFake implements _i7.GetUserCart {
  _FakeGetUserCart_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProduct_6 extends _i1.SmartFake implements _i8.Product {
  _FakeProduct_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_7 extends _i1.SmartFake implements _i9.LoginResponse {
  _FakeLoginResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCart_8 extends _i1.SmartFake implements _i10.Cart {
  _FakeCart_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeException_9 extends _i1.SmartFake implements Exception {
  _FakeException_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FakeStoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeStoreService extends _i1.Mock implements _i11.FakeStoreService {
  MockFakeStoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetProducts get getProductsUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getProductsUsecase),
            returnValue: _FakeGetProducts_0(
              this,
              Invocation.getter(#getProductsUsecase),
            ),
          )
          as _i2.GetProducts);

  @override
  _i3.GetProductDetail get getProductDetailUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getProductDetailUsecase),
            returnValue: _FakeGetProductDetail_1(
              this,
              Invocation.getter(#getProductDetailUsecase),
            ),
          )
          as _i3.GetProductDetail);

  @override
  _i4.Login get loginUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#loginUsecase),
            returnValue: _FakeLogin_2(this, Invocation.getter(#loginUsecase)),
          )
          as _i4.Login);

  @override
  _i5.GetCategories get getCategoriesUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getCategoriesUsecase),
            returnValue: _FakeGetCategories_3(
              this,
              Invocation.getter(#getCategoriesUsecase),
            ),
          )
          as _i5.GetCategories);

  @override
  _i6.GetProductByCategory get getProductsByCategoryUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getProductsByCategoryUsecase),
            returnValue: _FakeGetProductByCategory_4(
              this,
              Invocation.getter(#getProductsByCategoryUsecase),
            ),
          )
          as _i6.GetProductByCategory);

  @override
  _i7.GetUserCart get getUserCartUsecase =>
      (super.noSuchMethod(
            Invocation.getter(#getUserCartUsecase),
            returnValue: _FakeGetUserCart_5(
              this,
              Invocation.getter(#getUserCartUsecase),
            ),
          )
          as _i7.GetUserCart);

  @override
  _i12.Future<List<_i8.Product>> getProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, []),
            returnValue: _i12.Future<List<_i8.Product>>.value(<_i8.Product>[]),
          )
          as _i12.Future<List<_i8.Product>>);

  @override
  _i12.Future<_i8.Product> getProductDetail(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductDetail, [productId]),
            returnValue: _i12.Future<_i8.Product>.value(
              _FakeProduct_6(
                this,
                Invocation.method(#getProductDetail, [productId]),
              ),
            ),
          )
          as _i12.Future<_i8.Product>);

  @override
  _i12.Future<_i9.LoginResponse> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i12.Future<_i9.LoginResponse>.value(
              _FakeLoginResponse_7(
                this,
                Invocation.method(#login, [username, password]),
              ),
            ),
          )
          as _i12.Future<_i9.LoginResponse>);

  @override
  _i12.Future<List<String>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);

  @override
  _i12.Future<List<_i8.Product>> getProductsByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [category]),
            returnValue: _i12.Future<List<_i8.Product>>.value(<_i8.Product>[]),
          )
          as _i12.Future<List<_i8.Product>>);

  @override
  _i12.Future<_i10.Cart> getUserCart(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserCart, [userId]),
            returnValue: _i12.Future<_i10.Cart>.value(
              _FakeCart_8(this, Invocation.method(#getUserCart, [userId])),
            ),
          )
          as _i12.Future<_i10.Cart>);

  @override
  T handleEither<E, T>(_i13.Either<E, T>? either) =>
      (super.noSuchMethod(
            Invocation.method(#handleEither, [either]),
            returnValue: _i14.dummyValue<T>(
              this,
              Invocation.method(#handleEither, [either]),
            ),
          )
          as T);

  @override
  Exception mapFailureToException(dynamic failure) =>
      (super.noSuchMethod(
            Invocation.method(#mapFailureToException, [failure]),
            returnValue: _FakeException_9(
              this,
              Invocation.method(#mapFailureToException, [failure]),
            ),
          )
          as Exception);
}
